<?php
//
// File generated by Dolibarr installer 22.0.4 on Jan 17, 2026
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='https://bocci-petshop.rescat.life';
$dolibarr_main_document_root="/home/bayufada/bocci-petshop.rescat.life";
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt="/home/bayufada/bocci-petshop.rescat.life/custom";
$dolibarr_main_data_root="/home/bayufada/dolibarrdata";
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='0';
$dolibarr_main_db_name='bayufada_bocci_petshop';
$dolibarr_main_db_prefix='llxqy_';
$dolibarr_main_db_user='bayufada_bocci_petshop';
$dolibarr_main_db_pass='p2ml(V9S7)';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pg_restore, clamdscan, clamdscan.exe';
$dolibarr_nocsrfcheck='1';
$dolibarr_main_instance_unique_id='9d7b93efa1fcb2dfbb6b4e07d1917cf7';
$dolibarr_mailing_limit_sendbyweb='0';
$dolibarr_mailing_limit_sendbycli='0';

//$dolibarr_lib_FPDF_PATH="";
//$dolibarr_lib_TCPDF_PATH="";
//$dolibarr_lib_FPDI_PATH="";
//$dolibarr_lib_TCPDI_PATH="";
//$dolibarr_lib_GEOIP_PATH="";
//$dolibarr_lib_NUSOAP_PATH="";
//$dolibarr_lib_ODTPHP_PATH="";
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP="";
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
$dolibarr_main_distrib='standard';
